"🚀 enhancement":
  - changed-files:
      - any-glob-to-any-file:
          - "src/**/*"

"✍️ documentation":
  - changed-files:
      - any-glob-to-any-file:
          - "docs/**/*"

"🏠 chore":
  - changed-files:
      - any-glob-to-any-file:
          - ".github/**/*"
          - ".vscode/*"
